# Early loading screen configuration file
# reuse_early_window default: true
# enable_entrypoint_information default: true
# enable_mixin_pretransform default: false
# allow_early_window_close default: true
# window_creation_point available [default] options: postModLoading mixinEarly [mixinLoad] preLaunch mcEarly off
#
#Mon Jun 15 09:57:27 CEST 2026
enable_entrypoint_information=default
window_creation_point=default
allow_early_window_close=default
reuse_early_window=default
enable_mixin_pretransform=default
