#gdc-join
#Wed Jul 01 22:22:49 CEST 2026
retryIntervalSeconds=5
chunkSizeBytes=16384
terminalReasonKeywords=whitelist,ban,bandit,bannato,outdated,version,versione,incompat,full,pieno
connectScreenGta=true
statusUrl=https\://gdc-status.keem.workers.dev/status
entryFlowEnabled=true
restartDefaultSeconds=60
gateTimeoutSeconds=20
restartUrl=https\://gdc-status.keem.workers.dev/restart
f2Enabled=true
restartPollSeconds=4
f3Enabled=true
entryHost=gangdrogacity.xyz
budgetBytesPerTick=49152
autoRetry=true
restartToken=jdsicPZ8A0PubrMUuzr7xFpEpKOSbU76uFkOw5OCmAZqwVbhTsOHYv4h7X7oT4XU
