#gdc-join
#Sat Jun 20 06:11:42 CEST 2026
retryIntervalSeconds=5
f2Enabled=true
chunkSizeBytes=16384
terminalReasonKeywords=whitelist,ban,bandit,bannato,outdated,version,versione,incompat,full,pieno
connectScreenGta=true
entryFlowEnabled=true
f3Enabled=true
entryHost=gangdrogacity.xyz
budgetBytesPerTick=49152
gateTimeoutSeconds=20
autoRetry=true
