#gdc-join
#Fri Jun 26 20:19:55 EDT 2026
autoRetry=true
budgetBytesPerTick=49152
chunkSizeBytes=16384
connectScreenGta=true
entryFlowEnabled=true
entryHost=gangdrogacity.xyz
f2Enabled=true
f3Enabled=true
gateTimeoutSeconds=20
retryIntervalSeconds=5
terminalReasonKeywords=whitelist,ban,bandit,bannato,outdated,version,versione,incompat,full,pieno
statusUrl=https://gdc-status.keem.workers.dev/status
restartUrl=https://gdc-status.keem.workers.dev/restart
restartToken=jdsicPZ8A0PubrMUuzr7xFpEpKOSbU76uFkOw5OCmAZqwVbhTsOHYv4h7X7oT4XU
