#Indium properties file
#Thu Jun 04 21:01:59 CEST 2026
=\=\=\=\=\=\=
ambient-occlusion-mode=auto
always-tesselate-blocks=auto
>>>>>>>=parent of 4e3cdd6 (Add mods, configs and RPG loot table)
<<<<<<<=HEAD
