#Indium properties file
#Sun Jun 14 03:04:02 CEST 2026
=\=\=\=\=\=\=
ambient-occlusion-mode=auto
always-tesselate-blocks=auto
>>>>>>>=parent of 4e3cdd6 (Add mods, configs and RPG loot table)
<<<<<<<=HEAD
