#Indium properties file
#Sun Jun 14 05:38:44 CEST 2026
=\=\=\=\=\=\=
ambient-occlusion-mode=auto
always-tesselate-blocks=auto
>>>>>>>=parent of 4e3cdd6 (Add mods, configs and RPG loot table)
<<<<<<<=HEAD
