#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 04 01:24:20 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.8.1.zip
enableShaders=false
