#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 13 17:40:50 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=true
