#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Nov 22 03:21:52 CET 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=ComplementaryUnbound_r5.6.1.zip
enableShaders=true
