#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Mon Oct 20 01:36:15 CEST 2025
string.stealing.reputation_for_disabled_steal=-25
string.stealing.reputation_applied_for_steal=50
boolean.stealing.infinite_steal=false
