#Indigo properties file
#Sat Apr 11 15:15:39 CEST 2026
=\=\=\=\=\=\=
fix-mean-light-calculation=auto
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
ambient-occlusion-mode=hybrid
always-tesselate-blocks=auto
>>>>>>>=parent of 4e3cdd6 (Add mods, configs and RPG loot table)
fix-smooth-lighting-offset=auto
<<<<<<<=HEAD
fix-luminous-block-ambient-occlusion=auto
